-- AlterTable
ALTER TABLE "pedidos" ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMP;

-- AlterTable
ALTER TABLE "produtos" ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMP;

-- AlterTable
ALTER TABLE "usuarios" ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMP;
